"""Inline stub for the in-tree Rust extension ``fs_cache``.

The extension is built from ``crates/fs_cache`` and loaded as a bare
``.so`` (no PyPI package, no ``py.typed``), so mypy's self-check cannot
discover its types the way it discovers the ``ast_serialize`` wheel. This
stub mirrors the ``#[pymethods]`` surface defined in
``crates/fs_cache/src/lib.rs`` and is found via ``mypy_path``.
"""

from __future__ import annotations

__all__ = ["FsCache"]


class FsCache:
    def __init__(self) -> None: ...
    def set_package_root(self, package_root: list[str]) -> None: ...
    def flush(self) -> None: ...
    def stat_or_none(
        self, path: str
    ) -> tuple[int, int, float, int, int, int] | None: ...
    def init_under_package_root(self, path: str) -> bool: ...
    def listdir(self, path: str) -> list[str]: ...
    def isfile(self, path: str) -> bool: ...
    def isfile_case(self, path: str, prefix: str) -> bool: ...
    def exists_case(self, path: str, prefix: str) -> bool: ...
    def isdir(self, path: str) -> bool: ...
    def exists(self, path: str, real_only: bool = ...) -> bool: ...
    def read(self, path: str) -> bytes: ...
    def hash_digest(self, path: str) -> str: ...
    def samefile(self, f1: str, f2: str) -> bool: ...
