"""Native seam stubs for the server area (split from type_kernel.pyi, #1677)."""

from __future__ import annotations

from typing import Any, TypeVar

from mypy.nodes import (
    Decorator,
    MypyFile,
    OverloadedFuncDef,
    SymbolTable,
    SymbolTableNode,
    TypeInfo,
)

T = TypeVar("T")

def rust_read_cache_meta(blob: bytes) -> dict[str, Any] | None: ...
def rust_read_cache_meta_ex(blob: bytes) -> dict[str, Any] | None: ...
def rust_write_cache_meta(meta: Any) -> bytes | None: ...
def rust_write_cache_meta_ex(meta_ex: Any) -> bytes | None: ...
def rust_get_type_triggers(typ: Any, use_logical_deps: bool) -> list[str] | None: ...
def rust_attribute_triggers(typ: Any, name: str) -> list[str] | None: ...
def rust_walk_dependency_visitor(
    root: Any, type_map: dict[Any, Any], alias_deps: Any, use_logical_deps: bool
) -> dict[str, set[str]] | None: ...
def rust_walk_dependency_target(
    module_id: str, module_tree: Any, target: Any, type_map: dict[Any, Any]
) -> dict[str, set[str]] | None: ...

# Issue #570: fixup functions (live PyO3 objects)
def rust_fixup_type(typ: Any, modules: dict[str, MypyFile], allow_missing: bool) -> bool: ...
def rust_fixup_type_info(
    info: TypeInfo, modules: dict[str, MypyFile], allow_missing: bool
) -> bool: ...
def rust_resolve_cross_ref(
    value: SymbolTableNode, modules: dict[str, MypyFile], allow_missing: bool
) -> bool: ...
def rust_fixup_symbol_table(
    symtab: SymbolTable, modules: dict[str, MypyFile], allow_missing: bool
) -> bool: ...
def rust_fixup_overloaded_func_def(
    o: OverloadedFuncDef, modules: dict[str, MypyFile], allow_missing: bool
) -> bool: ...
def rust_fixup_decorator(
    d: Decorator, modules: dict[str, MypyFile], allow_missing: bool
) -> bool: ...

# mypy/server/deps.py — D2-style import-graph triggers.
def rust_compute_wildcard_triggers(
    changed_names: list[str], package_nesting_level: int
) -> list[str] | None: ...
def rust_compute_target_modules(
    triggers: list[str],
    deps: list[tuple[str, list[str]]],
    up_to_date_modules: list[str],
    module_ids: list[str],
) -> list[str]: ...

# mypy/server/update.py — daemon update helpers.
def rust_dedupe_modules(modules: list[tuple[str, str]]) -> list[tuple[str, str]]: ...
def rust_get_module_to_path_map(graph: Any) -> list[tuple[str, str]]: ...
def rust_get_sources(changed_modules: list[tuple[str, str]], followed: bool) -> list[Any]: ...
def rust_extract_fnam_from_message(message: str) -> str | None: ...
def rust_extract_possible_fnam_from_message(message: str) -> str: ...
def rust_sort_messages_preserving_file_order(
    messages: list[str], prev_messages: list[str]
) -> list[str]: ...
def rust_find_relative_leaf_module(
    modules: list[tuple[str, str]], deps: dict[str, list[str]]
) -> tuple[str, str] | None: ...
def rust_find_unloaded_deps(
    initial: list[str], graph: dict[str, tuple[list[str], list[str]]], loaded: set[str]
) -> list[str] | None: ...
def rust_target_from_node(module: str, node: Any) -> str | None: ...
def rust_merge_dependencies(new_deps: dict[str, set[str]], deps: dict[str, set[str]]) -> None: ...
def rust_non_trivial_bases(info: Any) -> list[Any]: ...
def rust_has_user_bases(info: Any) -> bool: ...
def rust_compare_symbol_table_snapshots(
    name_prefix: str, snapshot1: dict[str, Any], snapshot2: dict[str, Any]
) -> set[str]: ...
def rust_snapshot_type(typ: Any) -> tuple[Any, ...] | None: ...
def rust_snapshot_symbol_table(name_prefix: str, table: SymbolTable) -> dict[str, Any] | None: ...

# Phase G3.1 (#1670): read flip — the same builder over Rust-owned
# namespace storage, `None` when the store cannot mirror the table.
def rust_snapshot_symbol_table_shadow(
    name_prefix: str, table: SymbolTable
) -> dict[str, Any] | None: ...
def rust_is_expr_literal_type(node: Any) -> bool | None: ...
def rust_get_partial_instance_type(node: Any) -> Any | None: ...

# mypy/dmypy_server.py — daemon server helpers.
def rust_ignore_suppressed_imports(module: str) -> bool | None: ...
def rust_get_meminfo() -> dict[str, Any] | None: ...
def rust_response_metadata(options: Any) -> dict[str, str] | None: ...
def rust_find_all_sources_in_build(graph: Any, extra: Any) -> list[Any] | None: ...
def rust_add_all_sources_to_changed(sources: Any, changed: Any) -> None: ...
def rust_fix_module_deps(graph: Any) -> None: ...
def rust_filter_out_missing_top_level_packages(
    packages: Any, search_paths: Any, fscache: Any
) -> set[str] | None: ...

# Issue #540: pure helpers from mypy/modulefinder.py
def rust_is_init_file(path: str) -> bool: ...
def rust_parse_version(version: str) -> tuple[int, int]: ...
def rust_mypy_path() -> list[str]: ...
def rust_typeshed_py_version(options: Any) -> tuple[int, int]: ...
def rust_default_lib_path(
    data_dir: str, pyversion: tuple[int, int], custom_typeshed_dir: str | None
) -> list[str]: ...
def rust_load_stdlib_py_versions(
    custom_typeshed_dir: str | None,
) -> dict[str, tuple[tuple[int, int], tuple[int, int] | None]]: ...
def rust_matches_exclude(
    subpath: str, excludes: list[str], fscache: Any, verbose: bool
) -> bool: ...
def rust_get_search_dirs(python_executable: str | None) -> tuple[list[str], list[str]]: ...
def rust_compute_search_paths(
    sources: Any, options: Any, data_dir: str, alt_lib_path: str | None
) -> RustSearchPaths: ...

class RustSearchPaths:
    def __init__(
        self,
        python_path: list[str] = ...,
        mypy_path: list[str] = ...,
        package_path: list[str] = ...,
        typeshed_path: list[str] = ...,
    ) -> None: ...
    @property
    def python_path(self) -> tuple[str, ...]: ...
    @python_path.setter
    def python_path(self, value: list[str]) -> None: ...
    @property
    def mypy_path(self) -> tuple[str, ...]: ...
    @mypy_path.setter
    def mypy_path(self, value: list[str]) -> None: ...
    @property
    def package_path(self) -> tuple[str, ...]: ...
    @package_path.setter
    def package_path(self, value: list[str]) -> None: ...
    @property
    def typeshed_path(self) -> tuple[str, ...]: ...
    @typeshed_path.setter
    def typeshed_path(self, value: list[str]) -> None: ...
    def asdict(self) -> dict[str, tuple[str, ...]]: ...

class RustBuildSource:
    def __init__(
        self,
        path: str | None,
        module: str | None,
        text: str | None = ...,
        base_dir: str | None = ...,
        followed: bool = ...,
    ) -> None: ...
    @property
    def path(self) -> str | None: ...
    @path.setter
    def path(self, value: str | None) -> None: ...
    @property
    def module(self) -> str: ...
    @module.setter
    def module(self, value: str) -> None: ...
    @property
    def text(self) -> str | None: ...
    @text.setter
    def text(self, value: str | None) -> None: ...
    @property
    def base_dir(self) -> str | None: ...
    @base_dir.setter
    def base_dir(self, value: str | None) -> None: ...
    @property
    def followed(self) -> bool: ...
    @followed.setter
    def followed(self, value: bool) -> None: ...

class RustBuildSourceSet:
    def __init__(self, sources: Any) -> None: ...
    @property
    def source_text_present(self) -> bool: ...
    @property
    def source_modules(self) -> dict[str, str]: ...
    @property
    def source_paths(self) -> set[str]: ...
    def is_source(self, file: Any) -> bool: ...

def rust_process_start_options(flags: Any, allow_sources: bool) -> Any: ...

__all__ = [
    "rust_read_cache_meta",
    "rust_read_cache_meta_ex",
    "rust_write_cache_meta",
    "rust_write_cache_meta_ex",
    "rust_get_type_triggers",
    "rust_attribute_triggers",
    "rust_walk_dependency_visitor",
    "rust_walk_dependency_target",
    "rust_fixup_type",
    "rust_fixup_type_info",
    "rust_resolve_cross_ref",
    "rust_fixup_symbol_table",
    "rust_fixup_overloaded_func_def",
    "rust_fixup_decorator",
    "rust_compute_wildcard_triggers",
    "rust_compute_target_modules",
    "rust_dedupe_modules",
    "rust_get_module_to_path_map",
    "rust_get_sources",
    "rust_extract_fnam_from_message",
    "rust_extract_possible_fnam_from_message",
    "rust_sort_messages_preserving_file_order",
    "rust_find_relative_leaf_module",
    "rust_find_unloaded_deps",
    "rust_target_from_node",
    "rust_merge_dependencies",
    "rust_non_trivial_bases",
    "rust_has_user_bases",
    "rust_compare_symbol_table_snapshots",
    "rust_snapshot_type",
    "rust_snapshot_symbol_table",
    "rust_snapshot_symbol_table_shadow",
    "rust_is_expr_literal_type",
    "rust_get_partial_instance_type",
    "rust_ignore_suppressed_imports",
    "rust_get_meminfo",
    "rust_response_metadata",
    "rust_find_all_sources_in_build",
    "rust_add_all_sources_to_changed",
    "rust_fix_module_deps",
    "rust_filter_out_missing_top_level_packages",
    "rust_is_init_file",
    "rust_parse_version",
    "rust_mypy_path",
    "rust_typeshed_py_version",
    "rust_default_lib_path",
    "rust_load_stdlib_py_versions",
    "rust_matches_exclude",
    "rust_get_search_dirs",
    "rust_compute_search_paths",
    "RustSearchPaths",
    "RustBuildSource",
    "RustBuildSourceSet",
    "rust_process_start_options",
]
