name: code-review

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  ocr-review:
    runs-on: [self-hosted, macOS, ARM64, VidiomTM]
    if: vars.ENABLE_AI_CODE_REVIEW == 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Run OpenCodeReview
        run: ocr review
